#!/usr/bin/env bash
# Creates file
# Displays and deletes

function fun() {
	rm /var/run/holbertonscript.pid
	exit
}

trap "echo I hate the kill command;fun" SIGTERM
trap "echo Y U no love me?!;fun" SIGINT

echo $$ >> /var/run/holbertonscript.pid
while [ true ]; do
	echo To infinity and beyond;
done
