#!/usr/bin/env bash
# creates a subprocess

start_process() {
	    echo "Starting manage_my_process"
	        ./manage_my_process &
		    echo $! > /var/run/my_process.pid
		        echo "manage_my_process started"
		}

		stop_process() {
			    echo "Stopping manage_my_process"
			        if [ -f "/var/run/my_process.pid" ]; then
					        pid=$(cat /var/run/my_process.pid)
						        kill $pid
							        rm /var/run/my_process.pid
								        echo "manage_my_process stopped"
									    else
										            echo "manage_my_process is not running"
											        fi
											}

											restart_process() {
												    stop_process
												        start_process
													    echo "manage_my_process restarted"
												    }

												    case "$1" in
													        start)
															        start_process
																        ;;
																	    stop)
																		            stop_process
																			            ;;
																				        restart)
																						        restart_process
																							        ;;
																								    *)
																									            echo "Usage: manage_my_process {start|stop|restart}"
																										            exit 1
																											            ;;
																										    esac
