#!/usr/bin/env bash
# "bad luck at 4
# "good luck at 8
# "best school at other iterations

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 3 ]
	then
		echo "bad luck"
	elif [ $count -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best school"
	fi
	(( count++ ))
done
