#!/usr/bin/env bash
# Iterate numbers

count=1

while [ $count -le 20 ]
do
	echo "$count"
	case $count in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck form Italy";;
	esac
	(( count++ ))
done
